import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SiitHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="flex mt-20">Hi</div>
      </body>
    </div>
  );
}
