name: build and push any image to dockerhub

inputs:
  context:
    required: true
  tags:
    required: true
  username:
    required: true
  password:
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
