name: test when changes are applied to master

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test-backend:
    uses: ./.github/workflows/test-backend-app.yml

  test-git-server:
    uses: ./.github/workflows/test-project-in-docker.yml
    with:
      context: siithub-git-server

  publish-images:
    runs-on: ubuntu-latest

    needs: [test-backend, test-git-server]

    strategy:
      matrix:
        project: ["siithub-client", "siithub-backend", "siithub-git-server"]

    steps:
      - uses: actions/checkout@v3

      - uses: bjelicaluka/siithub/.github/actions/build-and-push@develop
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          context: ${{ matrix.project }}
          tags: panicmilos/${{ matrix.project }}:latest, panicmilos/${{ matrix.project }}:${{ github.run_number }}
